version: '3.1'

services:

  uchetka_web:
    image: php:7.2-apache
    container_name: uchetka
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
     - db
    volumes:
     - ./src/infoinpacts:/var/www/html/infoinpacts

  db:
    image: mariadb
    container_name: mysql
    restart: unless-stopped
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data_on_KA
      MYSQL_USER: analyst_connect
      MYSQL_PASSWORD: BG5&*VCYi12_
    ports:
      - 3306:3306
    volumes:
      - /var/db:/var/lib/mysql
      - /var/dumpbd:/var/backups/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 8080:80

  hive_to_web_converter:
    image: python:3.6
    #build: src/python
    container_name: converter
    #volumes:
     # -  ./src/converter/the_hive_to_web_converter:/opt/the_hive_to_web_converter
    #depends_on:
    #  - db
    #  - uchetka_web
    #command: python ./server.py
  

        
