version: "3.1"
services:
  uchetka_web:
    image: httpd:latest
  uchetka_db:
    image: mariadb:latest
  
  php:
   image: php:latest
  
  hconverter:
    build: HniveToWebConverter
  
  web:
    build: ucketka_bav